name: "web-app"
mode: "dev"
version: "1.0.1"
port: 8081
start_time: "2020-07-01"
machine_id: 1

log:
  level: "debug"
  filename: "web-app.log"
  max_size: 20
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "yhy3426356"
  dbname: "db1"
  max_open_connection: 1000
  max_idle_connection: 100

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100